language: node_js
node_js: 6
sudo: false
branches:
  only:
  - gh-pages
git:
  depth: 3
env:
  global:
    secure: NjVLbGVVixnrcDPPe/w5lip+TjEfz+N0mtqu58TnSDpIhKSEF7AwDfpaVtzQEcNvrPml8EemIf8zNUvGdjS1b1cvtwO+pg0gResPK1duHaerzYTIMhpsI0n4tHynhOcMWShMyTr1D6xUg8y/MSlEs/Sj3jJXSdFtJApvceQwoHny7upg7CiacnkzDQrRUIITlMyZcernYreB71YanXVkZqPs4PTK7DEbhoGZK+1VHCeiwAmtMMye+c8YtlD4nBKy5eWqLO3s1EWYvMFzvyT6qPyduckhbJH4O4UTzrRISchMufuOD4o2KvzslwOBzirH+HL7lqjzoa8fmUw1+1yZ/T40hgQa4B9uHBHm6xagpoZN5uGC1UTUskAr2uso/zugsgxaR+9pphYTtAsK6axN3eEsSXTU8/NRGSMo8gCjyCrJSgqvLizOnoEMN5rgaedSqP8LqAf6J4bjWcx4svBBcjCXvXWEOv9u1bKU0WpQEfn9SQQNDqCaKVb00FDNl3h0MuINRr3+us53t5eafnpYTjdZR2D8Hi8Q3j2KlY6nmYeZsonRqCw3L8Zt/8OvphXqXYVGZXuJFf7YDg5MNTrbOQeDG/LLkhhi6XhpZ4sV+ndwOp5ufW90cc65qMc0khxi5l5fau0CHmPf2jY+vJCfBnbOqCZKKyxBqJpP8tDXs5w=
script:
- npm run parking
- npm run verkeercentrum
after_success:
- git config --global push.default simple
- git config user.name "oSoc bot"
- git config user.email "hello+bot@haroen.me"
- git commit -am "update data [ci skip]"
- git status
- git push https://${GH_OAUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:gh-pages > /dev/null 2>&1
